# Generated by Django 3.0.3 on 2020-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200217_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_events',
            field=models.CharField(choices=[('bi', 'narozeniny'), ('na', 'svátek'), ('va', 'dovolená'), ('do', 'doctor'), ('ot', 'other')], default='ot', max_length=2),
        ),
    ]
