# Generated by Django 3.0.3 on 2020-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_type_of_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_repeats',
            field=models.IntegerField(default=1),
        ),
    ]
