# Generated by Django 3.0.3 on 2020-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_number_of_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_events',
            field=models.CharField(choices=[('narozeniny', 'narozeniny'), ('svátek', 'svátek'), ('dovolená', 'dovolená'), ('doctor', 'doctor'), ('other', 'other')], default='other', max_length=30),
        ),
    ]
