# Generated by Django 3.0.3 on 2020-02-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200219_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_repeats',
        ),
    ]
